[package]
name = "rust_cell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10.0"
rstar = "0.9.3"
crossbeam-channel = "0.5.6"
